TypeSoutanance:
    type: entity
    table: type_soutanance
    id:
        idTypesoutenance:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id_TypeSoutenance
            generator:
                strategy: IDENTITY
    fields:
        typeSoutenance:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
            column: Type_Soutenance
    lifecycleCallbacks: {  }
