Specialite:
    type: entity
    table: specialite
    indexes:
        Id_Departement:
            columns:
                - Id_Departement
    id:
        idSpecialite:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id_Specialite
            generator:
                strategy: IDENTITY
    fields:
        specialite:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
            column: Specialite
        diplome:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
            column: Diplome
    manyToOne:
        idDepartement:
            targetEntity: Departement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Id_Departement:
                    referencedColumnName: Id_Departement
            orphanRemoval: false
    lifecycleCallbacks: {  }
